<a href="https://colab.research.google.com/github/reachsriharsha/mycookbook/blob/master/5)_Data_Analysis_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1) Numpy Arrays

## Array Basics

In [ ]:
# 1D array

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [ ]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array(my_list)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
# 2D array

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## NumPy arrays using built in methods

In [ ]:
import numpy as np

In [ ]:
# 1) arange

In [ ]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# 2) zeros

In [ ]:
np.zeros(3) # 1D array

array([0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 3) ones

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# 4) linspace

In [ ]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [ ]:
# 5) eye

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# 6) arrays of random numbers (uniform distribution between 0 to 1)

In [ ]:
np.random.rand(5)

array([0.29171394, 0.36594606, 0.79993748, 0.95473512, 0.84347202])

In [ ]:
np.random.rand(4,4)

array([[0.98532681, 0.64693639, 0.94687943, 0.00873873],
       [0.58725729, 0.3137373 , 0.77553534, 0.70611488],
       [0.6226581 , 0.22488534, 0.20550848, 0.79488867],
       [0.47772067, 0.34103028, 0.98248219, 0.70365859]])

In [ ]:
# 7) Standard normal distribution or gaussion distribution

In [ ]:
np.random.randn(4) # 1D array

array([ 1.67117116,  1.00059651,  0.40529512, -0.01351253])

In [ ]:
np.random.randn(4,5)

array([[-0.98158601, -0.82718181,  0.21763841, -0.20589599, -0.37825558],
       [-0.12286885,  0.23824844, -0.67108337, -0.49428638,  1.44267504],
       [ 1.41378001, -0.76895591,  0.62255281, -0.7584776 , -2.21694264],
       [-0.16312332, -0.12494977,  0.21114099, -0.41619001,  0.78591205]])

In [ ]:
# 8) randint

In [ ]:
np.random.randint(0,100)

9

In [ ]:
np.random.randint(0,100,10)

array([85, 89, 53, 31,  9, 43, 94, 61, 74, 35])

## Useful attributes and methods

In [ ]:
arr = np.arange(25)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# reshape method

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(5,10)

ValueError: ignored

In [ ]:
# 2) max, min

In [ ]:
ran_arr = np.random.randint(0,50,10)

In [ ]:
ran_arr

array([25, 14, 49,  3, 37, 34, 37, 30, 19, 34])

In [ ]:
ran_arr.max()

49

In [ ]:
ran_arr.min()

3

In [ ]:
ran_arr.argmax()

2

In [ ]:
ran_arr.argmin()

3

In [ ]:
# 3) shape

In [ ]:
arr.shape

(25,)

In [ ]:
b = arr.reshape(5,5)

In [ ]:
b.shape

(5, 5)

In [ ]:
# 4) dtype

In [ ]:
arr.dtype

dtype('int64')

# 2) Numpy Indexing and Selection

## Indexing and Selection Basics

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10,21)

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[5]

15

In [ ]:
arr[0:5]

array([10, 11, 12, 13, 14])

In [ ]:
arr[2:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[:6]

array([10, 11, 12, 13, 14, 15])

## broadcasting the values

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [ ]:
arr = np.arange(10,21)

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
slice_arr = arr[0:6]

In [ ]:
slice_arr

array([10, 11, 12, 13, 14, 15])

In [ ]:
slice_arr[:] = 99

In [ ]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [ ]:
arr_cp = arr.copy()

In [ ]:
arr_cp

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [ ]:
arr[:] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr_cp

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_2 = arr[0:5]

In [ ]:
slice_2

array([0, 1, 2, 3, 4])

In [ ]:
slice_2[:] = 100

In [ ]:
slice_2

array([100, 100, 100, 100, 100])

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr_cp2 = arr.copy()

In [ ]:
arr_cp2[:] = 200

In [ ]:
arr_cp2

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Indexing a 2D array(Matrix)

In [ ]:
import numpy as np

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[0,0]

5

In [ ]:
arr_2d[1,0]

20

In [ ]:
arr_2d[0:2, 1:3]

array([[10, 15],
       [25, 30]])

## conditional selection

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
b = arr > 5

In [ ]:
b

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
arr[b]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr < 8]

array([0, 1, 2, 3, 4, 5, 6, 7])

# 3) Numpy Operations

In [ ]:
import numpy as np

In [ ]:
# array with array

In [ ]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# array with sclar

In [ ]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
arr - 50

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40])

In [ ]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
1/0

ZeroDivisionError: ignored

In [ ]:
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [ ]:
# universal array functions

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [ ]:
np.max(arr)

10

In [ ]:
np.min(arr)

0

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [ ]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])